"""add_template_table

Revision ID: 0675f8e4aa18
Revises: afef8278b356
Create Date: 2026-05-05 20:28:01.037552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0675f8e4aa18'
down_revision: Union[str, Sequence[str], None] = 'afef8278b356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('templates', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'template_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('templates', 'updated_at')
    op.drop_column('templates', 'created_at')
    # ### end Alembic commands ###
