"""add_template_document_tables

Revision ID: afef8278b356
Revises: 049e504758da
Create Date: 2026-05-05 20:26:11.040189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afef8278b356'
down_revision: Union[str, Sequence[str], None] = '049e504758da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version_target', sa.Enum('physician', 'patient', 'both', name='versiontarget'), nullable=False),
    sa.Column('field_type', sa.Enum('rich_text', 'supplement_table', 'auto_fill', 'locked_table', name='fieldtype'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('ai_prompt_hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('physician_id', sa.String(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', name='documentstatus'), nullable=False),
    sa.Column('sections_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supplement_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('header_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sections_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supplement_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('header_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_by', sa.String(), nullable=False),
    sa.Column('save_reason', sa.Enum('auto_save', 'manual_save', 'export', name='savereason'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_versions')
    op.drop_table('documents')
    op.drop_table('templates')
    # ### end Alembic commands ###
