"""add_templateSection_tables

Revision ID: be4bae181012
Revises: 0675f8e4aa18
Create Date: 2026-05-07 22:08:49.665582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4bae181012'
down_revision: Union[str, Sequence[str], None] = '0675f8e4aa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    version_target_enum = postgresql.ENUM(
        'physician', 'patient', 'both', name='versiontarget', create_type=False
    )
    field_type_enum = postgresql.ENUM(
        'rich_text', 'supplement_table', 'auto_fill', 'locked_table', name='fieldtype', create_type=False
    )
    primary_focus_enum = postgresql.ENUM(
        'hormones', 'metabolic', 'thyroid', 'fertility', 'genomics', 'general', name='primaryfocus', create_type=False
    )

    op.create_table('template_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('version_target', version_target_enum, nullable=False),
    sa.Column('field_type', field_type_enum, nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.Column('ai_prompt_hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('templates', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('templates', sa.Column('focus_category', primary_focus_enum, nullable=False))
    op.add_column('templates', sa.Column('version', sa.String(length=20), nullable=False))
    op.add_column('templates', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('templates', sa.Column('ai_system_prompt', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('created_by', sa.String(), nullable=True))
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('templates_template_id_fkey'), 'templates', type_='foreignkey')
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'])
    op.drop_column('templates', 'display_name')
    op.drop_column('templates', 'template_id')
    op.drop_column('templates', 'field_type')
    op.drop_column('templates', 'section_key')
    op.drop_column('templates', 'order_index')
    op.drop_column('templates', 'ai_prompt_hint')
    op.drop_column('templates', 'placeholder')
    op.drop_column('templates', 'version_target')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('version_target', postgresql.ENUM('physician', 'patient', 'both', name='versiontarget'), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('templates', sa.Column('ai_prompt_hint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('templates', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('section_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('field_type', postgresql.ENUM('rich_text', 'supplement_table', 'auto_fill', 'locked_table', name='fieldtype'), autoincrement=False, nullable=False))
    op.add_column('templates', sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('templates', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.create_foreign_key(op.f('templates_template_id_fkey'), 'templates', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.alter_column('templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('templates', 'created_by')
    op.drop_column('templates', 'description')
    op.drop_column('templates', 'ai_system_prompt')
    op.drop_column('templates', 'is_system')
    op.drop_column('templates', 'version')
    op.drop_column('templates', 'focus_category')
    op.drop_column('templates', 'name')
    op.drop_table('template_sections')
    # ### end Alembic commands ###
